import type { Metadata } from 'next'

import MainNav from '@/components/navigation/main-nav'
import Container from '@/components/ui/container'
import ThemeProvider from '@/providers/theme-provider'

import { urbanist } from './fonts'

import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: React.ReactNode
}

const RootLayout = ({ children }: RootLayoutProps) => {
	return (
		<html lang="en">
			<body className={urbanist.className}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
					<Container className="h-full">
						<MainNav />
						{children}
					</Container>
				</ThemeProvider>
			</body>
		</html>
	)
}

export default RootLayout
