import type { Metadata } from 'next'

import { urbanist } from './fonts'

import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: React.ReactNode
}

const RootLayout = ({ children }: RootLayoutProps) => {
	return (
		<html lang="en">
			<body className={urbanist.className}>{children}</body>
		</html>
	)
}

export default RootLayout
